services:
  mysql:
    image: mysql
    container_name: ${DOCKER_PROJECT_NAME}_db
    env_file: .env
    networks:
      - network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "${DOCKER_PROJECT_NAME}_db"]
        timeout: 10s
        retries: 10
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${DOCKER_PROJECT_NAME}_phpmyadmin
    env_file: .env
    networks:
      - network
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
    restart: always
    depends_on:
      - mysql
volumes:
  db_data:
networks:
  network:
    driver: bridge
    name: ${DOCKER_PROJECT_NAME}_network
